-- MySQL Script generated by MySQL Workbench
-- Sat Jul  3 17:21:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema notes_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notes_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notes_app` DEFAULT CHARACTER SET utf8 ;
USE `notes_app` ;

-- -----------------------------------------------------
-- Table `notes_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes_app`.`user` (
  `username` NVARCHAR(320) NOT NULL COMMENT 'Email or phone number',
  `name` NVARCHAR(500) NOT NULL,
  `accessCode` NVARCHAR(6) NULL,
  `accessCodeExpirationDate` BIGINT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notes_app`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes_app`.`note` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` NVARCHAR(500) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `datetime` BIGINT NOT NULL,
  `username` NVARCHAR(320) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Note_User_idx` (`username` ASC),
  CONSTRAINT `fk_Note_User`
    FOREIGN KEY (`username`)
    REFERENCES `notes_app`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `notes_app`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `notes_app`;
INSERT INTO `notes_app`.`user` (`username`, `name`, `accessCode`, `accessCodeExpirationDate`) VALUES ('jose@demo.com', 'José', NULL, NULL);
INSERT INTO `notes_app`.`user` (`username`, `name`, `accessCode`, `accessCodeExpirationDate`) VALUES ('+520123456789', 'Andrea', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `notes_app`.`note`
-- -----------------------------------------------------
START TRANSACTION;
USE `notes_app`;
INSERT INTO `notes_app`.`note` (`id`, `title`, `content`, `datetime`, `username`) VALUES (DEFAULT, 'Tareas pendientes', 'Lavar auto y cochera.', 1624660762000, 'jose@demo.com');
INSERT INTO `notes_app`.`note` (`id`, `title`, `content`, `datetime`, `username`) VALUES (DEFAULT, 'Pagos atrasados', 'Tarjeta de crédito.', 1624624762000, 'jose@demo.com');
INSERT INTO `notes_app`.`note` (`id`, `title`, `content`, `datetime`, `username`) VALUES (DEFAULT, 'Lista de compras', 'Frutas frescas.', 1624610362000, '+520123456789');

COMMIT;
